### ISSUE TITLE
Feedback on Just Enough Cython

### ISSUE THREAD

**Issue by wshanks** [pmbaumgartner/personal-hugo-site#2]
I learned about your [blog post on Cython](https://www.peterbaumgartner.com/blog/intro-to-just-enough-cython-to-be-useful/) from the recent [Python Bytes episode](https://pythonbytes.fm/episodes/show/277/) that covered it. It is a really nice write up and makes doing a little bit of Cython really accessible.

I just wanted to suggest one other point that I didn't see mentioned in your post -- often working with numpy is good enough without reaching for Cython. For example, for the case you considered, I tried this alternate version:

```python
import numpy
from numpy.typing import NDArray

def count_increases(depths: NDArray[np.int32]) -> int:
    return np.sum(depths[1:] > depths[:-1])
```

For my testing on 5,000 item lists/arrays, I got:

| case | Python | Cythonized Python | Typed Cython | Numpy Cython | Numpy Python |
| --- | --- | ---  |  --- | --- | ---  | 
| Time (us) | 201 | 94 | 23 | 3.8 | 9.6 |

So the Cythonized solution is the best but is only about a factor of 2.5 faster than calling standard numpy functions from Python. So there might be an extra point to consider in your conditions for when to use Cython -- has the code already been optimized to use numpy in a performant way? The cases that would benefit most from Cython might be ones where you need to operate on arrays with a little bit of unusual logic not likely to be captured by numpy functions.

**Comment by pmbaumgartner** [comment]
hey @wshanks - thanks for the comment and additional benchmarking!

I totally agree with you, there's a question to be asked prior to solving any sort of optimization problem: what's the best framework to do this in? To your point, I think you might be able to get even better performance if you were to compile your function with [numba](https://numba.pydata.org/). I actually did this for a project at my past employer when we were optimizing a large simulation -- basically throwing everything in arrays makes lots of stuff faster 😄 

Benchmarks aside, what I like about Cython, and why I chose to focus on it here, is that you can stick to more of a traditional programming paradigm rather than having to _think in arrays_, like you do with `numpy`. I bet if you looked at other problems from Advent of Code (where I stole this problem), they're probably easier to reason about in a traditional programming sense compared to thinking about them as array manipulations. The incrementalism is nice too, you could just start out by solving them with python and compiling that for a speedup, and not have to think too hard about how you need to change your program.
